services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - path: .env
        required: true
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: